# Form implementation generated from reading ui file 'UIes/Window_Deals_c_add.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Deals_c_add(object):
    def setupUi(self, Dialog_Deals_c_add):
        Dialog_Deals_c_add.setObjectName("Dialog_Deals_c_add")
        Dialog_Deals_c_add.resize(568, 347)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog_Deals_c_add)
        self.buttonBox.setGeometry(QtCore.QRect(210, 300, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.frame_3 = QtWidgets.QFrame(parent=Dialog_Deals_c_add)
        self.frame_3.setGeometry(QtCore.QRect(10, 90, 531, 211))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.sp_deal_c_cpercent = QtWidgets.QDoubleSpinBox(parent=self.frame_3)
        self.sp_deal_c_cpercent.setGeometry(QtCore.QRect(410, 140, 71, 32))
        self.sp_deal_c_cpercent.setObjectName("sp_deal_c_cpercent")
        self.te_deal_c_cost = QtWidgets.QPlainTextEdit(parent=self.frame_3)
        self.te_deal_c_cost.setGeometry(QtCore.QRect(20, 140, 171, 31))
        self.te_deal_c_cost.setStyleSheet("")
        self.te_deal_c_cost.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.te_deal_c_cost.setLineWidth(1)
        self.te_deal_c_cost.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.te_deal_c_cost.setObjectName("te_deal_c_cost")
        self.te_deal_c_buyer = QtWidgets.QPlainTextEdit(parent=self.frame_3)
        self.te_deal_c_buyer.setGeometry(QtCore.QRect(230, 90, 171, 31))
        self.te_deal_c_buyer.setStyleSheet("")
        self.te_deal_c_buyer.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.te_deal_c_buyer.setLineWidth(1)
        self.te_deal_c_buyer.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.te_deal_c_buyer.setObjectName("te_deal_c_buyer")
        self.te_deal_c_name = QtWidgets.QPlainTextEdit(parent=self.frame_3)
        self.te_deal_c_name.setGeometry(QtCore.QRect(20, 30, 261, 31))
        self.te_deal_c_name.setStyleSheet("")
        self.te_deal_c_name.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.te_deal_c_name.setLineWidth(1)
        self.te_deal_c_name.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.te_deal_c_name.setObjectName("te_deal_c_name")
        self.te_deal_c_csum = QtWidgets.QPlainTextEdit(parent=self.frame_3)
        self.te_deal_c_csum.setGeometry(QtCore.QRect(230, 140, 171, 31))
        self.te_deal_c_csum.setStyleSheet("")
        self.te_deal_c_csum.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.te_deal_c_csum.setLineWidth(1)
        self.te_deal_c_csum.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.te_deal_c_csum.setObjectName("te_deal_c_csum")
        self.te_deal_c_object = QtWidgets.QPlainTextEdit(parent=self.frame_3)
        self.te_deal_c_object.setGeometry(QtCore.QRect(20, 90, 171, 31))
        self.te_deal_c_object.setStyleSheet("")
        self.te_deal_c_object.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.te_deal_c_object.setLineWidth(1)
        self.te_deal_c_object.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.te_deal_c_object.setObjectName("te_deal_c_object")
        self.cb_deal_c_type = QtWidgets.QComboBox(parent=self.frame_3)
        self.cb_deal_c_type.setGeometry(QtCore.QRect(310, 30, 191, 32))
        self.cb_deal_c_type.setObjectName("cb_deal_c_type")
        self.cb_deal_c_type.addItem("")
        self.cb_deal_c_type.addItem("")
        self.label = QtWidgets.QLabel(parent=Dialog_Deals_c_add)
        self.label.setGeometry(QtCore.QRect(30, 40, 501, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog_Deals_c_add)
        self.buttonBox.accepted.connect(Dialog_Deals_c_add.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_Deals_c_add.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_Deals_c_add)

    def retranslateUi(self, Dialog_Deals_c_add):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Deals_c_add.setWindowTitle(_translate("Dialog_Deals_c_add", "Dialog"))
        self.te_deal_c_cost.setPlaceholderText(_translate("Dialog_Deals_c_add", "Стоимость сделки"))
        self.te_deal_c_buyer.setPlaceholderText(_translate("Dialog_Deals_c_add", "Покупатель"))
        self.te_deal_c_name.setPlaceholderText(_translate("Dialog_Deals_c_add", "Наименование сделки"))
        self.te_deal_c_csum.setPlaceholderText(_translate("Dialog_Deals_c_add", "Комиссия риелтора"))
        self.te_deal_c_object.setPlaceholderText(_translate("Dialog_Deals_c_add", "ID Объекта"))
        self.cb_deal_c_type.setPlaceholderText(_translate("Dialog_Deals_c_add", "Тип сделки"))
        self.cb_deal_c_type.setItemText(0, _translate("Dialog_Deals_c_add", "Аренда"))
        self.cb_deal_c_type.setItemText(1, _translate("Dialog_Deals_c_add", "Продажа"))
        self.label.setText(_translate("Dialog_Deals_c_add", "Оформить сделку"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Deals_c_add = QtWidgets.QDialog()
    ui = Ui_Dialog_Deals_c_add()
    ui.setupUi(Dialog_Deals_c_add)
    Dialog_Deals_c_add.show()
    sys.exit(app.exec())
