# Form implementation generated from reading ui file 'UIes/Window_Enter.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 270)
        self.frame_enter = QtWidgets.QFrame(parent=Form)
        self.frame_enter.setGeometry(QtCore.QRect(40, 20, 531, 221))
        self.frame_enter.setStyleSheet("")
        self.frame_enter.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_enter.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_enter.setObjectName("frame_enter")
        self.bt_enter = QtWidgets.QPushButton(parent=self.frame_enter)
        self.bt_enter.setGeometry(QtCore.QRect(230, 170, 131, 34))
        self.bt_enter.setTabletTracking(False)
        self.bt_enter.setObjectName("bt_enter")
        self.te_enter_login = QtWidgets.QLineEdit(parent=self.frame_enter)
        self.te_enter_login.setGeometry(QtCore.QRect(140, 60, 221, 32))
        self.te_enter_login.setTabletTracking(True)
        self.te_enter_login.setObjectName("te_enter_login")
        self.te_enter_password = QtWidgets.QLineEdit(parent=self.frame_enter)
        self.te_enter_password.setGeometry(QtCore.QRect(140, 120, 221, 32))
        self.te_enter_password.setTabletTracking(True)
        self.te_enter_password.setObjectName("te_enter_password")
        self.label = QtWidgets.QLabel(parent=self.frame_enter)
        self.label.setGeometry(QtCore.QRect(10, 20, 511, 18))
        self.label.setObjectName("label")
        self.bt_enter_settings = QtWidgets.QPushButton(parent=self.frame_enter)
        self.bt_enter_settings.setGeometry(QtCore.QRect(460, 170, 46, 46))
        self.bt_enter_settings.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_enter_settings.setTabletTracking(True)
        self.bt_enter_settings.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.bt_enter_settings.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UIes/../Icons/icons8-settings-100.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_enter_settings.setIcon(icon)
        self.bt_enter_settings.setIconSize(QtCore.QSize(30, 30))
        self.bt_enter_settings.setObjectName("bt_enter_settings")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.bt_enter.setText(_translate("Form", "Войти"))
        self.te_enter_login.setPlaceholderText(_translate("Form", "Логин"))
        self.te_enter_password.setPlaceholderText(_translate("Form", "Пароль"))
        self.label.setText(_translate("Form", "Введите данные учетной записи для доступа к приложению"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
