# Form implementation generated from reading ui file 'UIes/Window_Deals_add.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Deals_add(object):
    def setupUi(self, Dialog_Deals_add):
        Dialog_Deals_add.setObjectName("Dialog_Deals_add")
        Dialog_Deals_add.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        Dialog_Deals_add.resize(563, 347)
        Dialog_Deals_add.setStyleSheet("")
        Dialog_Deals_add.setSizeGripEnabled(False)
        Dialog_Deals_add.setModal(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog_Deals_add)
        self.buttonBox.setGeometry(QtCore.QRect(210, 300, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.frame = QtWidgets.QFrame(parent=Dialog_Deals_add)
        self.frame.setGeometry(QtCore.QRect(650, 110, 120, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(parent=Dialog_Deals_add)
        self.frame_2.setGeometry(QtCore.QRect(10, 70, 531, 211))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.sp_deal_cpercent = QtWidgets.QDoubleSpinBox(parent=self.frame_2)
        self.sp_deal_cpercent.setGeometry(QtCore.QRect(410, 140, 71, 32))
        self.sp_deal_cpercent.setObjectName("sp_deal_cpercent")
        self.te_deal_cost = QtWidgets.QPlainTextEdit(parent=self.frame_2)
        self.te_deal_cost.setGeometry(QtCore.QRect(20, 140, 171, 31))
        self.te_deal_cost.setStyleSheet("")
        self.te_deal_cost.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.te_deal_cost.setLineWidth(1)
        self.te_deal_cost.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.te_deal_cost.setObjectName("te_deal_cost")
        self.te_deal_client = QtWidgets.QPlainTextEdit(parent=self.frame_2)
        self.te_deal_client.setGeometry(QtCore.QRect(230, 90, 171, 31))
        self.te_deal_client.setStyleSheet("")
        self.te_deal_client.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.te_deal_client.setLineWidth(1)
        self.te_deal_client.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.te_deal_client.setObjectName("te_deal_client")
        self.te_deal_name = QtWidgets.QPlainTextEdit(parent=self.frame_2)
        self.te_deal_name.setGeometry(QtCore.QRect(20, 30, 261, 31))
        self.te_deal_name.setStyleSheet("")
        self.te_deal_name.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.te_deal_name.setLineWidth(1)
        self.te_deal_name.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.te_deal_name.setObjectName("te_deal_name")
        self.te_deal_csum = QtWidgets.QPlainTextEdit(parent=self.frame_2)
        self.te_deal_csum.setGeometry(QtCore.QRect(230, 140, 171, 31))
        self.te_deal_csum.setStyleSheet("")
        self.te_deal_csum.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.te_deal_csum.setLineWidth(1)
        self.te_deal_csum.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.te_deal_csum.setObjectName("te_deal_csum")
        self.te_deal_object = QtWidgets.QPlainTextEdit(parent=self.frame_2)
        self.te_deal_object.setGeometry(QtCore.QRect(20, 90, 171, 31))
        self.te_deal_object.setStyleSheet("")
        self.te_deal_object.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.te_deal_object.setLineWidth(1)
        self.te_deal_object.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.te_deal_object.setObjectName("te_deal_object")
        self.cb_deal_type = QtWidgets.QComboBox(parent=self.frame_2)
        self.cb_deal_type.setGeometry(QtCore.QRect(310, 30, 191, 32))
        self.cb_deal_type.setObjectName("cb_deal_type")
        self.cb_deal_type.addItem("")
        self.cb_deal_type.addItem("")
        self.label = QtWidgets.QLabel(parent=Dialog_Deals_add)
        self.label.setGeometry(QtCore.QRect(30, 20, 501, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_2.raise_()
        self.buttonBox.raise_()
        self.frame.raise_()
        self.label.raise_()

        self.retranslateUi(Dialog_Deals_add)
        self.buttonBox.accepted.connect(Dialog_Deals_add.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_Deals_add.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_Deals_add)

    def retranslateUi(self, Dialog_Deals_add):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Deals_add.setWindowTitle(_translate("Dialog_Deals_add", "Dialog"))
        self.te_deal_cost.setPlaceholderText(_translate("Dialog_Deals_add", "Стоимость сделки"))
        self.te_deal_client.setPlaceholderText(_translate("Dialog_Deals_add", "Клиент"))
        self.te_deal_name.setPlaceholderText(_translate("Dialog_Deals_add", "Наименование сделки"))
        self.te_deal_csum.setPlaceholderText(_translate("Dialog_Deals_add", "Комиссия риелтора"))
        self.te_deal_object.setPlaceholderText(_translate("Dialog_Deals_add", "ID Объекта"))
        self.cb_deal_type.setPlaceholderText(_translate("Dialog_Deals_add", "Тип сделки"))
        self.cb_deal_type.setItemText(0, _translate("Dialog_Deals_add", "Аренда"))
        self.cb_deal_type.setItemText(1, _translate("Dialog_Deals_add", "Продажа"))
        self.label.setText(_translate("Dialog_Deals_add", "Оформить сделку"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Deals_add = QtWidgets.QDialog()
    ui = Ui_Dialog_Deals_add()
    ui.setupUi(Dialog_Deals_add)
    Dialog_Deals_add.show()
    sys.exit(app.exec())
