# Form implementation generated from reading ui file 'UIes/Window_Guests_add.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Guests_add(object):
    def setupUi(self, Dialog_Guests_add):
        Dialog_Guests_add.setObjectName("Dialog_Guests_add")
        Dialog_Guests_add.resize(264, 167)
        Dialog_Guests_add.setStyleSheet("")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog_Guests_add)
        self.buttonBox.setGeometry(QtCore.QRect(50, 110, 181, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.te_gue_fullname = QtWidgets.QTextEdit(parent=Dialog_Guests_add)
        self.te_gue_fullname.setGeometry(QtCore.QRect(20, 20, 211, 26))
        self.te_gue_fullname.setTabletTracking(False)
        self.te_gue_fullname.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.te_gue_fullname.setStyleSheet("")
        self.te_gue_fullname.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.te_gue_fullname.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.te_gue_fullname.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.te_gue_fullname.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.te_gue_fullname.setTabChangesFocus(False)
        self.te_gue_fullname.setUndoRedoEnabled(True)
        self.te_gue_fullname.setOverwriteMode(False)
        self.te_gue_fullname.setAcceptRichText(True)
        self.te_gue_fullname.setObjectName("te_gue_fullname")
        self.te_gue_phone = QtWidgets.QTextEdit(parent=Dialog_Guests_add)
        self.te_gue_phone.setGeometry(QtCore.QRect(20, 70, 211, 26))
        self.te_gue_phone.setTabletTracking(False)
        self.te_gue_phone.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.te_gue_phone.setStyleSheet("")
        self.te_gue_phone.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.te_gue_phone.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.te_gue_phone.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.te_gue_phone.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.te_gue_phone.setTabChangesFocus(False)
        self.te_gue_phone.setUndoRedoEnabled(True)
        self.te_gue_phone.setOverwriteMode(False)
        self.te_gue_phone.setAcceptRichText(True)
        self.te_gue_phone.setObjectName("te_gue_phone")

        self.retranslateUi(Dialog_Guests_add)
        self.buttonBox.accepted.connect(Dialog_Guests_add.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_Guests_add.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_Guests_add)

    def retranslateUi(self, Dialog_Guests_add):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Guests_add.setWindowTitle(_translate("Dialog_Guests_add", "Dialog"))
        self.te_gue_fullname.setPlaceholderText(_translate("Dialog_Guests_add", "ФИО"))
        self.te_gue_phone.setPlaceholderText(_translate("Dialog_Guests_add", "Номер телефона"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Guests_add = QtWidgets.QDialog()
    ui = Ui_Dialog_Guests_add()
    ui.setupUi(Dialog_Guests_add)
    Dialog_Guests_add.show()
    sys.exit(app.exec())
