# Form implementation generated from reading ui file 'UIes/Window_ServicesHist_add.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_ServiceHist_add(object):
    def setupUi(self, Dialog_ServiceHist_add):
        Dialog_ServiceHist_add.setObjectName("Dialog_ServiceHist_add")
        Dialog_ServiceHist_add.resize(524, 280)
        Dialog_ServiceHist_add.setStyleSheet("")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog_ServiceHist_add)
        self.buttonBox.setGeometry(QtCore.QRect(170, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.te_sh_client = QtWidgets.QTextEdit(parent=Dialog_ServiceHist_add)
        self.te_sh_client.setGeometry(QtCore.QRect(20, 80, 131, 26))
        self.te_sh_client.setTabletTracking(False)
        self.te_sh_client.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.te_sh_client.setStyleSheet("")
        self.te_sh_client.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.te_sh_client.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.te_sh_client.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.te_sh_client.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.te_sh_client.setTabChangesFocus(False)
        self.te_sh_client.setUndoRedoEnabled(True)
        self.te_sh_client.setOverwriteMode(False)
        self.te_sh_client.setAcceptRichText(True)
        self.te_sh_client.setObjectName("te_sh_client")
        self.dtpicker_sh_date = QtWidgets.QDateTimeEdit(parent=Dialog_ServiceHist_add)
        self.dtpicker_sh_date.setGeometry(QtCore.QRect(20, 120, 194, 32))
        self.dtpicker_sh_date.setObjectName("dtpicker_sh_date")
        self.te_sh_service = QtWidgets.QTextEdit(parent=Dialog_ServiceHist_add)
        self.te_sh_service.setGeometry(QtCore.QRect(20, 180, 311, 26))
        self.te_sh_service.setTabletTracking(False)
        self.te_sh_service.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.te_sh_service.setStyleSheet("")
        self.te_sh_service.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.te_sh_service.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.te_sh_service.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.te_sh_service.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.te_sh_service.setTabChangesFocus(False)
        self.te_sh_service.setUndoRedoEnabled(True)
        self.te_sh_service.setOverwriteMode(False)
        self.te_sh_service.setAcceptRichText(True)
        self.te_sh_service.setObjectName("te_sh_service")
        self.te_sh_cost = QtWidgets.QTextEdit(parent=Dialog_ServiceHist_add)
        self.te_sh_cost.setGeometry(QtCore.QRect(370, 180, 121, 26))
        self.te_sh_cost.setTabletTracking(False)
        self.te_sh_cost.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.te_sh_cost.setStyleSheet("")
        self.te_sh_cost.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.te_sh_cost.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.te_sh_cost.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.te_sh_cost.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.te_sh_cost.setTabChangesFocus(False)
        self.te_sh_cost.setUndoRedoEnabled(True)
        self.te_sh_cost.setOverwriteMode(False)
        self.te_sh_cost.setAcceptRichText(True)
        self.te_sh_cost.setObjectName("te_sh_cost")
        self.label = QtWidgets.QLabel(parent=Dialog_ServiceHist_add)
        self.label.setGeometry(QtCore.QRect(20, 20, 291, 37))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(parent=Dialog_ServiceHist_add)
        self.frame.setGeometry(QtCore.QRect(10, 10, 501, 221))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.buttonBox.raise_()
        self.te_sh_client.raise_()
        self.dtpicker_sh_date.raise_()
        self.te_sh_service.raise_()
        self.te_sh_cost.raise_()
        self.label.raise_()

        self.retranslateUi(Dialog_ServiceHist_add)
        self.buttonBox.accepted.connect(Dialog_ServiceHist_add.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_ServiceHist_add.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_ServiceHist_add)

    def retranslateUi(self, Dialog_ServiceHist_add):
        _translate = QtCore.QCoreApplication.translate
        Dialog_ServiceHist_add.setWindowTitle(_translate("Dialog_ServiceHist_add", "Dialog"))
        self.te_sh_client.setPlaceholderText(_translate("Dialog_ServiceHist_add", "ID Клиента"))
        self.te_sh_service.setPlaceholderText(_translate("Dialog_ServiceHist_add", "Наименование услуги"))
        self.te_sh_cost.setPlaceholderText(_translate("Dialog_ServiceHist_add", "Стоимость"))
        self.label.setText(_translate("Dialog_ServiceHist_add", "Оформить услугу"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_ServiceHist_add = QtWidgets.QDialog()
    ui = Ui_Dialog_ServiceHist_add()
    ui.setupUi(Dialog_ServiceHist_add)
    Dialog_ServiceHist_add.show()
    sys.exit(app.exec())
