# Form implementation generated from reading ui file 'UIes/Window_Requests_add.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Requests_add(object):
    def setupUi(self, Dialog_Requests_add):
        Dialog_Requests_add.setObjectName("Dialog_Requests_add")
        Dialog_Requests_add.resize(514, 386)
        Dialog_Requests_add.setStyleSheet("")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog_Requests_add)
        self.buttonBox.setGeometry(QtCore.QRect(160, 340, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.frame = QtWidgets.QFrame(parent=Dialog_Requests_add)
        self.frame.setGeometry(QtCore.QRect(10, 60, 491, 261))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.te_req_details = QtWidgets.QPlainTextEdit(parent=self.frame)
        self.te_req_details.setGeometry(QtCore.QRect(10, 60, 461, 181))
        self.te_req_details.setStyleSheet("")
        self.te_req_details.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.te_req_details.setLineWidth(1)
        self.te_req_details.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.te_req_details.setObjectName("te_req_details")
        self.te_req_client = QtWidgets.QPlainTextEdit(parent=self.frame)
        self.te_req_client.setGeometry(QtCore.QRect(10, 10, 171, 31))
        self.te_req_client.setStyleSheet("")
        self.te_req_client.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.te_req_client.setLineWidth(1)
        self.te_req_client.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.te_req_client.setObjectName("te_req_client")
        self.label = QtWidgets.QLabel(parent=Dialog_Requests_add)
        self.label.setGeometry(QtCore.QRect(20, 20, 381, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame.raise_()
        self.buttonBox.raise_()
        self.label.raise_()

        self.retranslateUi(Dialog_Requests_add)
        self.buttonBox.accepted.connect(Dialog_Requests_add.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_Requests_add.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_Requests_add)

    def retranslateUi(self, Dialog_Requests_add):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Requests_add.setWindowTitle(_translate("Dialog_Requests_add", "Dialog"))
        self.te_req_details.setPlaceholderText(_translate("Dialog_Requests_add", "Описание запроса"))
        self.te_req_client.setPlaceholderText(_translate("Dialog_Requests_add", "ID Клиента"))
        self.label.setText(_translate("Dialog_Requests_add", "Добавить запрос на поиск объекта"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Requests_add = QtWidgets.QDialog()
    ui = Ui_Dialog_Requests_add()
    ui.setupUi(Dialog_Requests_add)
    Dialog_Requests_add.show()
    sys.exit(app.exec())
