# Form implementation generated from reading ui file 'UIes/Window_Meeting_add.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Meetings_add(object):
    def setupUi(self, Dialog_Meetings_add):
        Dialog_Meetings_add.setObjectName("Dialog_Meetings_add")
        Dialog_Meetings_add.resize(478, 346)
        Dialog_Meetings_add.setStyleSheet("")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog_Meetings_add)
        self.buttonBox.setGeometry(QtCore.QRect(110, 310, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.frame_3 = QtWidgets.QFrame(parent=Dialog_Meetings_add)
        self.frame_3.setGeometry(QtCore.QRect(20, 20, 441, 281))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.te_met_name = QtWidgets.QTextEdit(parent=self.frame_3)
        self.te_met_name.setGeometry(QtCore.QRect(20, 70, 291, 26))
        self.te_met_name.setTabletTracking(False)
        self.te_met_name.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.te_met_name.setStyleSheet("")
        self.te_met_name.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.te_met_name.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.te_met_name.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.te_met_name.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.te_met_name.setTabChangesFocus(False)
        self.te_met_name.setUndoRedoEnabled(True)
        self.te_met_name.setOverwriteMode(False)
        self.te_met_name.setAcceptRichText(True)
        self.te_met_name.setObjectName("te_met_name")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(20, 110, 91, 18))
        self.label_7.setObjectName("label_7")
        self.te_met_desc = QtWidgets.QTextEdit(parent=self.frame_3)
        self.te_met_desc.setGeometry(QtCore.QRect(20, 170, 391, 81))
        self.te_met_desc.setTabletTracking(False)
        self.te_met_desc.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.te_met_desc.setStyleSheet("")
        self.te_met_desc.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.te_met_desc.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.te_met_desc.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.te_met_desc.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.te_met_desc.setTabChangesFocus(False)
        self.te_met_desc.setUndoRedoEnabled(True)
        self.te_met_desc.setOverwriteMode(False)
        self.te_met_desc.setAcceptRichText(True)
        self.te_met_desc.setObjectName("te_met_desc")
        self.dtpicker_met_datetime = QtWidgets.QDateTimeEdit(parent=self.frame_3)
        self.dtpicker_met_datetime.setGeometry(QtCore.QRect(20, 130, 194, 32))
        self.dtpicker_met_datetime.setObjectName("dtpicker_met_datetime")
        self.label = QtWidgets.QLabel(parent=self.frame_3)
        self.label.setGeometry(QtCore.QRect(10, 10, 403, 37))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog_Meetings_add)
        self.buttonBox.accepted.connect(Dialog_Meetings_add.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_Meetings_add.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_Meetings_add)

    def retranslateUi(self, Dialog_Meetings_add):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Meetings_add.setWindowTitle(_translate("Dialog_Meetings_add", "Назначьте встречу"))
        self.te_met_name.setPlaceholderText(_translate("Dialog_Meetings_add", "Наименование"))
        self.label_7.setText(_translate("Dialog_Meetings_add", "Дата и время"))
        self.te_met_desc.setPlaceholderText(_translate("Dialog_Meetings_add", "Описание"))
        self.label.setText(_translate("Dialog_Meetings_add", "Назначить встречу"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Meetings_add = QtWidgets.QDialog()
    ui = Ui_Dialog_Meetings_add()
    ui.setupUi(Dialog_Meetings_add)
    Dialog_Meetings_add.show()
    sys.exit(app.exec())
