# Form implementation generated from reading ui file 'UIes/Window_Pictures.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_pictures(object):
    def setupUi(self, Dialog_pictures):
        Dialog_pictures.setObjectName("Dialog_pictures")
        Dialog_pictures.resize(1000, 500)
        Dialog_pictures.setStyleSheet("")
        self.lb_pix = QtWidgets.QLabel(parent=Dialog_pictures)
        self.lb_pix.setEnabled(True)
        self.lb_pix.setGeometry(QtCore.QRect(60, 30, 871, 381))
        self.lb_pix.setStyleSheet("")
        self.lb_pix.setScaledContents(True)
        self.lb_pix.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_pix.setObjectName("lb_pix")
        self.bt_back = QtWidgets.QPushButton(parent=Dialog_pictures)
        self.bt_back.setGeometry(QtCore.QRect(710, 460, 88, 34))
        self.bt_back.setObjectName("bt_back")
        self.bt_next = QtWidgets.QPushButton(parent=Dialog_pictures)
        self.bt_next.setGeometry(QtCore.QRect(820, 460, 88, 34))
        self.bt_next.setObjectName("bt_next")
        self.bt_delphoto = QtWidgets.QPushButton(parent=Dialog_pictures)
        self.bt_delphoto.setGeometry(QtCore.QRect(20, 460, 101, 34))
        self.bt_delphoto.setObjectName("bt_delphoto")

        self.retranslateUi(Dialog_pictures)
        QtCore.QMetaObject.connectSlotsByName(Dialog_pictures)

    def retranslateUi(self, Dialog_pictures):
        _translate = QtCore.QCoreApplication.translate
        Dialog_pictures.setWindowTitle(_translate("Dialog_pictures", "Dialog"))
        self.lb_pix.setText(_translate("Dialog_pictures", "TextLabel"))
        self.bt_back.setText(_translate("Dialog_pictures", "<<"))
        self.bt_next.setText(_translate("Dialog_pictures", ">>"))
        self.bt_delphoto.setText(_translate("Dialog_pictures", "Удалить фото"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_pictures = QtWidgets.QDialog()
    ui = Ui_Dialog_pictures()
    ui.setupUi(Dialog_pictures)
    Dialog_pictures.show()
    sys.exit(app.exec())
