# Form implementation generated from reading ui file 'UIes/Window_Impressions_add.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Impressions_add(object):
    def setupUi(self, Dialog_Impressions_add):
        Dialog_Impressions_add.setObjectName("Dialog_Impressions_add")
        Dialog_Impressions_add.resize(397, 195)
        Dialog_Impressions_add.setStyleSheet("")
        self.frame = QtWidgets.QFrame(parent=Dialog_Impressions_add)
        self.frame.setGeometry(QtCore.QRect(10, 50, 371, 121))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.frame)
        self.buttonBox.setGeometry(QtCore.QRect(160, 70, 191, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.te_imp_object = QtWidgets.QTextEdit(parent=self.frame)
        self.te_imp_object.setGeometry(QtCore.QRect(10, 20, 121, 26))
        self.te_imp_object.setTabletTracking(False)
        self.te_imp_object.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.te_imp_object.setStyleSheet("")
        self.te_imp_object.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.te_imp_object.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.te_imp_object.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.te_imp_object.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.te_imp_object.setTabChangesFocus(False)
        self.te_imp_object.setUndoRedoEnabled(True)
        self.te_imp_object.setOverwriteMode(False)
        self.te_imp_object.setAcceptRichText(True)
        self.te_imp_object.setObjectName("te_imp_object")
        self.te_imp_guest = QtWidgets.QTextEdit(parent=self.frame)
        self.te_imp_guest.setGeometry(QtCore.QRect(10, 70, 121, 26))
        self.te_imp_guest.setTabletTracking(False)
        self.te_imp_guest.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.te_imp_guest.setStyleSheet("")
        self.te_imp_guest.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.te_imp_guest.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.te_imp_guest.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.te_imp_guest.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.te_imp_guest.setTabChangesFocus(False)
        self.te_imp_guest.setUndoRedoEnabled(True)
        self.te_imp_guest.setOverwriteMode(False)
        self.te_imp_guest.setAcceptRichText(True)
        self.te_imp_guest.setObjectName("te_imp_guest")
        self.dtpicker_imp_datetime = QtWidgets.QDateTimeEdit(parent=self.frame)
        self.dtpicker_imp_datetime.setGeometry(QtCore.QRect(160, 20, 194, 32))
        self.dtpicker_imp_datetime.setObjectName("dtpicker_imp_datetime")
        self.label = QtWidgets.QLabel(parent=Dialog_Impressions_add)
        self.label.setGeometry(QtCore.QRect(10, 10, 391, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog_Impressions_add)
        self.buttonBox.accepted.connect(Dialog_Impressions_add.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_Impressions_add.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_Impressions_add)

    def retranslateUi(self, Dialog_Impressions_add):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Impressions_add.setWindowTitle(_translate("Dialog_Impressions_add", "Планирование показов"))
        self.te_imp_object.setPlaceholderText(_translate("Dialog_Impressions_add", "ID Объекта"))
        self.te_imp_guest.setPlaceholderText(_translate("Dialog_Impressions_add", "ID Гостя"))
        self.label.setText(_translate("Dialog_Impressions_add", "Запланировать показ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Impressions_add = QtWidgets.QDialog()
    ui = Ui_Dialog_Impressions_add()
    ui.setupUi(Dialog_Impressions_add)
    Dialog_Impressions_add.show()
    sys.exit(app.exec())
